version: 2
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A frist hello"
    sally:
      docker:
        - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "Double trouble"
workflows:
  version: 2
  boby_sally:
    job:
      - bobby
      - sally
